const httpStatuses = {
    OK: 200,
    CREATED: 201,
    BAD_HTTP_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    RESOURSE_NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    NETWORK_AUTHENTICATION_REQUIRED: 511,
}
export default httpStatuses
